name: Test Installs

on: 
  push: 

jobs:
  build-image:
    runs-on: macOS-latest
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: Who am I? Who am I? What are you even saying?
        run: |
          echo `whoami`
          dscl . list /Users | grep -v “^_”
      - name: Demotion
        run: |
          sudo dseditgroup -o edit -d `whoami` -t user admin
      - name: r u admin tho
        run: |
          if groups `whoami` | grep -q -w admin; 
          then 
            echo "Is admin. :)"; 
          else 
            echo "YOU SHALL NOT PASS!!! >:("; 
          fi
      - name: Brewery
        run: |
          which brew
          mkdir homebrew && curl -L https://github.com/Homebrew/brew/tarball/master | tar xz --strip 1 -C homebrew
          which brew
      - name: Install
        run: |
          brew install coreutils redis mysql mysql-client
          brew install --cask postman atom sourcetree beyond-compare
      - name: But did it brew?
        run: |
          brew list | grep -f coreutils redis mysql mysql-client
          brew list --cask | grep -f postman atom sourcetree beyond-compare
